version: "3.8"

services:
  amicultivated_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: amicultivated_backend
    restart: unless-stopped
    networks:
      - internal-network
    environment:
      - NODE_ENV=production
      - API=3000
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DB_HOST=sqlite
      - DB_PORT=/app/data/database.sqlite
      - ART_PROVIDER=${ART_PROVIDER:-wikidata}
      - HTTPS_PROXY=http://squid:3128
    volumes:
      - ./data:/app/data
    depends_on:
      - squid

  amicultivated_frontend:
    build:
      context: ./amicultivated_frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    container_name: amicultivated_frontend
    restart: unless-stopped
    networks:
      - internal-network
    depends_on:
      - amicultivated_backend

  squid:
    image: ubuntu/squid
    container_name: amicultivated_squid
    restart: unless-stopped
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
    networks:
      - internal-network
      - web-network

networks:
  internal-network:
    external: true
  web-network:
    driver: bridge
