version: "3.8"

services:
  amicultivated_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: amicultivated_backend
    restart: unless-stopped
    networks:
      - internal-network
      - external-network
    environment:
      - NODE_ENV=production
      - API=3000
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DB_HOST=sqlite
      - DB_PORT=/app/data/database.sqlite
      - ART_PROVIDER=${ART_PROVIDER:-database}

    volumes:
      - ./data:/app/data

  amicultivated_frontend:
    build:
      context: ./amicultivated_frontend
      dockerfile: Dockerfile
      network: host
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    container_name: amicultivated_frontend
    restart: unless-stopped
    networks:
      - internal-network
    depends_on:
      - amicultivated_backend

networks:
  internal-network:
    external: true
  external-network:
    external: true
